# Generated by Django 5.2.4 on 2025-09-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小(字节)')),
                ('file_prefix', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件前缀')),
                ('record_type', models.CharField(blank=True, choices=[('data', '数据用量'), ('voice', '语音用量'), ('smsc', '短信中心'), ('used', '已使用'), ('imei', '设备识别码'), ('locu', '位置更新')], max_length=10, null=True, verbose_name='记录类型')),
                ('host_node', models.CharField(blank=True, max_length=50, null=True, verbose_name='主机节点')),
                ('cdr_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='CDR类型')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='版本')),
                ('file_date', models.CharField(blank=True, max_length=8, null=True, verbose_name='文件日期')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('success', '处理成功'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('total_iccid_count', models.IntegerField(default=0, verbose_name='ICCID总数')),
                ('processed_iccid_count', models.IntegerField(default=0, verbose_name='已处理ICCID数')),
                ('success_iccid_count', models.IntegerField(default=0, verbose_name='成功处理ICCID数')),
                ('failed_iccid_count', models.IntegerField(default=0, verbose_name='失败ICCID数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '文档',
                'verbose_name_plural': '文档管理',
                'db_table': 'document_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='document_do_status_6e1808_idx'), models.Index(fields=['file_date', 'record_type'], name='document_do_file_da_694e18_idx')],
            },
        ),
        migrations.CreateModel(
            name='BadCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iccid', models.CharField(max_length=20, verbose_name='ICCID')),
                ('api_type', models.CharField(choices=[('user', '用户信息'), ('subscription', '订阅信息'), ('usage', '用量信息')], max_length=20, verbose_name='API类型')),
                ('trans_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='事务ID')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP状态码')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='完整JSON响应')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('last_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='最后重试时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bad_cases', to='document.document', verbose_name='关联文档')),
            ],
            options={
                'verbose_name': '错误案例',
                'verbose_name_plural': '错误案例管理',
                'db_table': 'document_badcase',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', 'api_type'], name='document_ba_documen_b3f76a_idx'), models.Index(fields=['iccid', 'created_at'], name='document_ba_iccid_3f05f2_idx'), models.Index(fields=['status_code', 'created_at'], name='document_ba_status__ef22ac_idx')],
                'constraints': [models.UniqueConstraint(fields=('document', 'iccid', 'api_type'), name='unique_badcase_document_iccid_api')],
            },
        ),
    ]
