# Generated by Django 5.2.4 on 2025-09-17 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ICC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriptionId', models.CharField(max_length=64, unique=True, verbose_name='订阅ID')),
                ('userId', models.BigIntegerField(blank=True, null=True, verbose_name='用户ID')),
                ('acctId', models.BigIntegerField(blank=True, null=True, verbose_name='账户ID')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌')),
                ('productId', models.CharField(blank=True, max_length=16, null=True, verbose_name='产品ID')),
                ('productFlag', models.CharField(blank=True, choices=[('0', '基础套餐'), ('1', '附加包')], max_length=1, null=True, verbose_name='产品标志')),
                ('status', models.CharField(blank=True, choices=[('0', '订阅中'), ('1', '未激活'), ('2', '正常'), ('3', '已过期'), ('4', '退订中'), ('5', '已锁定')], max_length=1, null=True, verbose_name='订阅状态')),
                ('statusTime', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='状态时间格式：yyyyMMddHHmmss', regex='^\\d{14}$')], verbose_name='状态时间')),
                ('activeDeadline', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='最后激活时间格式：yyyyMMdd', regex='^\\d{8}$')], verbose_name='最后激活时间')),
                ('validityUnit', models.CharField(blank=True, choices=[('H', '小时'), ('D', '日历日'), ('M', '日历月'), ('N', '永不过期')], max_length=1, null=True, verbose_name='有效期单位')),
                ('validityTime', models.IntegerField(blank=True, null=True, verbose_name='有效期时长')),
                ('effTime', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='生效时间格式：yyyyMMddHHmmss', regex='^\\d{14}$')], verbose_name='生效时间')),
                ('expTime', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='过期时间格式：yyyyMMddHHmmss', regex='^\\d{14}$')], verbose_name='过期时间')),
                ('createTime', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='创建时间格式：yyyyMMddHHmmss', regex='^\\d{14}$')], verbose_name='创建时间')),
                ('priority', models.CharField(blank=True, choices=[('20', '最高'), ('30', '高'), ('40', '中'), ('50', '低'), ('80', '最低')], max_length=2, null=True, verbose_name='产品优先级')),
                ('changeReason', models.CharField(blank=True, choices=[('1', '使用中'), ('2', '速度受限'), ('3', '已用尽'), ('4', '未激活，已过期'), ('5', '未激活，已退订'), ('6', '已激活，已过期'), ('7', '已激活，已退订')], max_length=1, null=True, verbose_name='订阅变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('icc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='ICC.icc', verbose_name='ICC卡')),
            ],
            options={
                'verbose_name': '订阅',
                'verbose_name_plural': '订阅管理',
                'db_table': 'subscription_subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
