# Generated by Django 5.2.4 on 2025-09-17 03:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usageDate', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='用量日期格式：yyyyMMdd', regex='^\\d{8}$')], verbose_name='用量日期')),
                ('productId', models.CharField(blank=True, max_length=16, null=True, verbose_name='产品ID')),
                ('subscriptionId', models.CharField(blank=True, max_length=64, null=True, verbose_name='订阅ID')),
                ('usageType', models.CharField(blank=True, choices=[('dat', '数据'), ('sms', '短信'), ('voc', '语音')], max_length=10, null=True, verbose_name='用量类型')),
                ('callType', models.CharField(blank=True, choices=[('0', '主叫 (MO)'), ('1', '被叫 (MT)'), ('*', '全部 (ALL)')], max_length=1, null=True, verbose_name='呼叫类型')),
                ('visitMcc', models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator(message='访问地MCC必须是3位数字', regex='^\\d{3}$')], verbose_name='访问地MCC')),
                ('visitMnc', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='访问地MNC必须是1-6位数字', regex='^\\d{1,6}$')], verbose_name='访问地MNC')),
                ('usage', models.BigIntegerField(blank=True, null=True, verbose_name='用量值')),
                ('unit', models.CharField(blank=True, choices=[('Byte', '字节'), ('Minute', '分钟'), ('String', '条')], max_length=10, null=True, verbose_name='用量单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='Subscription.subscription', verbose_name='订阅')),
            ],
            options={
                'verbose_name': '用量',
                'verbose_name_plural': '用量管理',
                'db_table': 'usage_usage',
                'ordering': ['-usageDate', '-created_at'],
                'indexes': [models.Index(fields=['usageDate', 'subscriptionId'], name='usage_usage_usageDa_30b2ac_idx'), models.Index(fields=['usageDate', 'productId'], name='usage_usage_usageDa_615ca7_idx'), models.Index(fields=['usageType', 'usageDate'], name='usage_usage_usageTy_34301f_idx')],
                'constraints': [models.UniqueConstraint(fields=('usageDate', 'subscription', 'productId', 'visitMnc'), name='unique_usage_per_day_subscription_product_mnc')],
            },
        ),
    ]
